server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: 'jdbc:mysql://49.232.228.46 :3306/yubi'
      username: sean
      password: zhuxiaoyao99
  # Redis 配置
  # todo 需替换配置
#  redis:
#    database: 1
#    host: localhost
#    port: 6379
#    timeout: 5000
#    password: 123456
  # Elasticsearch 配置
  # todo 需替换配置
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''

yuapi:
  client:
    access-key: p7g7ghkdtzne3tdqa0rptx8h0l4ufpno
    secret-key: i2egoai7413zwh41v5vvb5nehql78gaw